Resources:
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: my-lambda-bucket
        S3Key: lambda_function.zip
      Handler: lambda_function.handler
      Runtime: python3.8
      Timeout: 60
      MemorySize: 128

  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-lambda-bucket

  MyLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt MyLambdaFunction.Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Join [":", ["arn:aws:s3:::", !Ref MyS3Bucket]]

Outputs:
  MyLambdaFunctionArn:
    Value: !GetAtt MyLambdaFunction.Arn
